<?php

namespace IngSoft\DatBundle\Repository;

use Doctrine\ORM\EntityRepository;
use IngSoft\DatBundle\Entity\Empresas as Empresas;
/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
     /**
     * Permite crear una empresa nuevo en la base de datos, la nit la empresa
     * no puede estar repetido
     * 
     * 
     * @param \IngSoft\DatBundle\Entity\Empresas $empresa
     *                                           empresa nueva en la base de datos
     * 
     * 
     * @return true si la empresa se pudo agregar, false si no fue así
     * 
     */
    public function create(Empresas $empresa) {
        $em = $this->getEntityManager();
        $empresaU = $em->find($this->getEntityName(), $empresa->getCodigo());
        if (!$empresaU) {
            $em->persist($empresa);
            $em->flush();
            return true;
        }
        return false;
    }

     /**
     * Permite actualizar a una empresa que se encuentre en la base de datos
     * la empresa recibido tiene los atributos nuevos
     * 
     * 
     * @param \IngSoft\DatBundle\Entity\Empresas $empresa
     *                                           empresa con los datos nuevos
     * 
     * @return true si se pudo actualizar, false si no fue así
     */
    public function update(Empresas $empresa) {
        $em = $this->getEntityManager();
        $empresaU = $em->find($this->getEntityName(), $empresa->getCodigo());
        if ($empresaU) {
            $em->persist($empresa);
            $em->flush();
            return true;
        }
        return false;
    }

    /**
     * Permite buscar a una empresa según su cedula
     * 
     * 
     * @param type $nit
     *        nit dla empresa que se quiere buscar
     * 
     * @return empresa encontrado
     * 
     */
    public function find($nit) {
        $em = $this->getEntityManager();
        $empresaU = $em->find($this->getEntityManager(), $nit);
        return $empresaU;
    }

    /**
     * Permite obtener todos los registros de los empresas
     * 
     * 
     * @return todos los empresas de la base de datos
     */
    public function getAll() {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM Empresas p");
        return $query->getResult();
    }

    /**
     * Permite borrar a una empresa según su cedula
     * 
     * 
     * @param type $nit
     *             nit dla empresa que se quiere borrar
     * 
     * @return true si se puede borrar, false si no fue así
     */
    public function delete($nit) {
        $em = $this->getEntityManager();
        $empresaU = $em->find($this->getEntityManager(), $nit);
        if (!$empresaU) {
            $em->remove($empresaU);
            $em->flush();
            return true;
        }
        return false;
    }
    
}
