<?php

namespace IngSoft\DatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstitutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutoRepository extends EntityRepository
{
}
