<?php

namespace IngSoft\DatBundle\Repository;

use Doctrine\ORM\EntityRepository;
use IngSoft\DatBundle\Entity\Objetivos as Objetivos;
/**
 * ObjetivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetivoRepository extends EntityRepository
{
     /**
     * Permite crear un objetivo nuevo en la base de datos, el codigo del objetivo
     * no puede estar repetido
     * 
     * 
     * @param \IngSoft\DatBundle\Entity\Objetivos $objetivo
     *                                           objetivo nuevo en la base de datos
     * 
     * 
     * @return true si el objetivo se pudo agregar, false si no fue así
     * 
     */
    public function create(Objetivos $objetivo) {
        $em = $this->getEntityManager();
        $objetivoU = $em->find($this->getEntityName(), $objetivo->getCodigo());
        if (!$objetivoU) {
            $em->persist($objetivo);
            $em->flush();
            return true;
        }
        return false;
    }

     /**
     * Permite actualizar a un objetivo que se encuentre en la base de datos
     * el objetivo recibido tiene los atributos nuevos
     * 
     * 
     * @param \IngSoft\DatBundle\Entity\Objetivos $objetivo
     *                                           objetivo con los datos nuevos
     * 
     * @return true si se pudo actualizar, false si no fue así
     */
    public function update(Objetivos $objetivo) {
        $em = $this->getEntityManager();
        $objetivoU = $em->find($this->getEntityName(), $objetivo->getCodigo());
        if ($objetivoU) {
            $em->persist($objetivo);
            $em->flush();
            return true;
        }
        return false;
    }

    /**
     * Permite buscar a un objetivo según su cedula
     * 
     * 
     * @param type $codigo
     *        codigo del objetivo que se quiere buscar
     * 
     * @return objetivo encontrado
     * 
     */
    public function find($codigo) {
        $em = $this->getEntityManager();
        $objetivoU = $em->find($this->getEntityManager(), $codigo);
        return $objetivoU;
    }

    /**
     * Permite obtener todos los registros de los objetivos
     * 
     * 
     * @return todos los objetivos de la base de datos
     */
    public function getAll() {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM Objetivos p");
        return $query->getResult();
    }

    /**
     * Permite borrar a un objetivo según su cedula
     * 
     * 
     * @param type $codigo
     *             codigo del objetivo que se quiere borrar
     * 
     * @return true si se puede borrar, false si no fue así
     */
    public function delete($codigo) {
        $em = $this->getEntityManager();
        $objetivoU = $em->find($this->getEntityManager(), $codigo);
        if (!$objetivoU) {
            $em->remove($objetivoU);
            $em->flush();
            return true;
        }
        return false;
    }
    
    
}
