<?php

namespace IngSoft\DatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PenalizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenalizacionRepository extends EntityRepository
{
}
