<?php

namespace IngSoft\DatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecursoNoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecursoNoticiaRepository extends EntityRepository
{
}
