<?php

namespace IngSoft\DatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends EntityRepository
{
    /**
     * Permite crear un solicitud nuevo en la base de datos, el codigo del solicitud
     * no puede estar repetido
     * 
     * 
     * @param \IngSoft\DatBundle\Entity\Objetivos $solicitud
     *                                           solicitud nuevo en la base de datos
     * 
     * 
     * @return true si el solicitud se pudo agregar, false si no fue así
     * 
     */
    public function create(Objetivos $solicitud) {
        $em = $this->getEntityManager();
        $solicitudU = $em->find($this->getEntityName(), $solicitud->getCodigo());
        if (!$solicitudU) {
            $em->persist($solicitud);
            $em->flush();
            return true;
        }
        return false;
    }

     /**
     * Permite actualizar a un solicitud que se encuentre en la base de datos
     * el solicitud recibido tiene los atributos nuevos
     * 
     * 
     * @param \IngSoft\DatBundle\Entity\Objetivos $solicitud
     *                                           solicitud con los datos nuevos
     * 
     * @return true si se pudo actualizar, false si no fue así
     */
    public function update(Objetivos $solicitud) {
        $em = $this->getEntityManager();
        $solicitudU = $em->find($this->getEntityName(), $solicitud->getCodigo());
        if ($solicitudU) {
            $em->persist($solicitud);
            $em->flush();
            return true;
        }
        return false;
    }

    /**
     * Permite buscar a un solicitud según su cedula
     * 
     * 
     * @param type $codigo
     *        codigo del solicitud que se quiere buscar
     * 
     * @return solicitud encontrado
     * 
     */
    public function find($codigo) {
        $em = $this->getEntityManager();
        $solicitudU = $em->find($this->getEntityManager(), $codigo);
        return $solicitudU;
    }

    /**
     * Permite obtener todos los registros de los solicituds
     * 
     * 
     * @return todos los solicituds de la base de datos
     */
    public function getAll() {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM Objetivos p");
        return $query->getResult();
    }

    /**
     * Permite borrar a un solicitud según su cedula
     * 
     * 
     * @param type $codigo
     *             codigo del solicitud que se quiere borrar
     * 
     * @return true si se puede borrar, false si no fue así
     */
    public function delete($codigo) {
        $em = $this->getEntityManager();
        $solicitudU = $em->find($this->getEntityManager(), $codigo);
        if (!$solicitudU) {
            $em->remove($solicitudU);
            $em->flush();
            return true;
        }
        return false;
    }
    
    public function solicitudesCategoria($codigoCategoria){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT s FROM Solicitudes s JOIN s.foro f "
                . "JOIN f.categoria c WHERE c.codigo=:codigo");
    }
}
