Aspectos:
    type: entity
    table: aspectos
    fields:
        codigo:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 30
            fixed: false
            nullable: false
        calificacion:
            type: decimal
            nullable: false
        porcentajeInfluencia:
            type: decimal
            nullable: false
            column: porcentaje_influencia
    manyToOne:
        codigoPrueba:
            targetEntity: PruebasTecnicas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigo_prueba:
                    referencedColumnName: codigo
            orphanRemoval: false
    lifecycleCallbacks: {  }
