CalificacionesPrestadores:
    type: entity
    table: calificaciones_prestadores
    fields:
        codigo:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        actual:
            type: boolean
            nullable: false
    manyToOne:
        codigoCalificacion:
            targetEntity: Calificaciones
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigo_calificacion:
                    referencedColumnName: codigo
            orphanRemoval: false
        codigoPrestador:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigo_prestador:
                    referencedColumnName: cedula
            orphanRemoval: false
    lifecycleCallbacks: {  }
