Departamentos:
    type: entity
    table: departamentos
    fields:
        codigo:
            id: true
            type: string
            length: 10
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 30
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
