Foros:
    type: entity
    table: foros
    fields:
        codigo:
            id: true
            type: string
            length: 20
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 60
            fixed: false
            nullable: false
        descripcion:
            type: text
            nullable: false
    manyToOne:
        codigoCategoria:
            targetEntity: Categorias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigo_categoria:
                    referencedColumnName: codigo
            orphanRemoval: false
    lifecycleCallbacks: {  }
