Institutos:
    type: entity
    table: institutos
    fields:
        codigo:
            id: true
            type: string
            length: 20
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        direccion:
            type: string
            length: 90
            fixed: false
            nullable: false
    manyToOne:
        codigoBarrio:
            targetEntity: Barrios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigo_barrio:
                    referencedColumnName: codigo
            orphanRemoval: false
    lifecycleCallbacks: {  }
