Usuarios:
    type: entity
    table: usuarios
    fields:
        cedula:
            id: true
            type: string
            length: 20
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 60
            fixed: false
            nullable: false
        correo:
            type: string
            length: 60
            fixed: false
            nullable: false
        direccion:
            type: string
            length: 90
            fixed: false
            nullable: false
        telefonoDomicilio:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: telefono_domicilio
        telefonoCelular:
            type: string
            length: 20
            fixed: false
            nullable: false
            column: telefono_celular
        correoElectronico:
            type: string
            length: 60
            fixed: false
            nullable: false
            column: correo_electronico
        fechaInscripcion:
            type: datetime
            nullable: false
            column: fecha_inscripcion
        perfilActivo:
            type: boolean
            nullable: false
            column: perfil_activo
        contrasenia:
            type: string
            length: 30
            fixed: false
            nullable: false
        codigoPerfil:
            type: integer
            unsigned: false
            nullable: false
            column: codigo_perfil
        eliminado:
            type: boolean
            nullable: false
    manyToMany:
        codigoActividad:
            targetEntity: Actividades
            cascade: {  }
            mappedBy: null
            inversedBy: codigoPrestador
            joinTable:
                name: prestadores_actividades
                joinColumns:
                    -
                        name: codigo_prestador
                        referencedColumnName: cedula
                inverseJoinColumns:
                    -
                        name: codigo_actividad
                        referencedColumnName: codigo
            orderBy: null
        codigoProyecto:
            targetEntity: Proyectos
            cascade: {  }
            mappedBy: codigoPrestador
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        codigoTipo:
            targetEntity: TiposUsuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigo_tipo:
                    referencedColumnName: codigo
            orphanRemoval: false
        codigoBarrio:
            targetEntity: Barrios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                codigo_barrio:
                    referencedColumnName: codigo
            orphanRemoval: false
    lifecycleCallbacks: {  }
